// GENERATED by @edgedb/generate v0.0.7
// Run 'npx @edgedb/generate edgeql-js' to re-generate

import * as $ from "../reflection.mjs";
import * as _ from "../imports.mjs";
const Role = $.makeType(_.spec, "16a0a1e8-bce5-11ed-a6a8-ed4719dbfde7", _.syntax.literal);

const $HasTimestamp = $.makeType(_.spec, "169e4362-bce5-11ed-aad8-3137ce08c83e", _.syntax.literal);

const HasTimestamp= _.syntax.$PathNode($.$toSet($HasTimestamp, $.Cardinality.Many), null);

const $Comment = $.makeType(_.spec, "169f6e9a-bce5-11ed-bc95-291739ba819c", _.syntax.literal);

const Comment= _.syntax.$PathNode($.$toSet($Comment, $.Cardinality.Many), null);

const $Post = $.makeType(_.spec, "16a56f5c-bce5-11ed-b822-bd748f7efdd1", _.syntax.literal);

const Post= _.syntax.$PathNode($.$toSet($Post, $.Cardinality.Many), null);

const $Tag = $.makeType(_.spec, "16a411fc-bce5-11ed-a508-5d7587d3d042", _.syntax.literal);

const Tag= _.syntax.$PathNode($.$toSet($Tag, $.Cardinality.Many), null);

const $User = $.makeType(_.spec, "16a0ad78-bce5-11ed-b3d1-7bf59907d7b4", _.syntax.literal);

const User= _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null);



export { Role, $HasTimestamp, HasTimestamp, $Comment, Comment, $Post, Post, $Tag, Tag, $User, User };

const __defaultExports = {
  "Role": Role,
  "HasTimestamp": HasTimestamp,
  "Comment": Comment,
  "Post": Post,
  "Tag": Tag,
  "User": User
};
export default __defaultExports;
