// GENERATED by @edgedb/generate v0.0.7
// Run 'npx @edgedb/generate edgeql-js' to re-generate

import * as $ from "../reflection.mjs";
import * as _ from "../imports.mjs";
const AccessKind = $.makeType(_.spec, "1c1ed0fc-b413-11ed-936c-c1c1a6ac8a9c", _.syntax.literal);

const AccessPolicyAction = $.makeType(_.spec, "1c1e7328-b413-11ed-bad5-0dc590cbd42e", _.syntax.literal);

const Cardinality = $.makeType(_.spec, "1c1be3ec-b413-11ed-9657-51252e08efb0", _.syntax.literal);

const OperatorKind = $.makeType(_.spec, "1c1cfeda-b413-11ed-be0d-43f9c466af1b", _.syntax.literal);

const ParameterKind = $.makeType(_.spec, "1c1dbcbc-b413-11ed-95d8-679e5f605b8b", _.syntax.literal);

const SourceDeleteAction = $.makeType(_.spec, "1c1c9cce-b413-11ed-a725-81ab10f9aea5", _.syntax.literal);

const TargetDeleteAction = $.makeType(_.spec, "1c1c4242-b413-11ed-845b-df356eac77f2", _.syntax.literal);

const TypeModifier = $.makeType(_.spec, "1c1e1842-b413-11ed-8b63-9f058deeaa0e", _.syntax.literal);

const Volatility = $.makeType(_.spec, "1c1d61e0-b413-11ed-91df-7310b68a4261", _.syntax.literal);

const $Object_1c1f4050b41311edb0b05d846e82c666 = $.makeType(_.spec, "1c1f4050-b413-11ed-b0b0-5d846e82c666", _.syntax.literal);

const Object_1c1f4050b41311edb0b05d846e82c666= _.syntax.$PathNode($.$toSet($Object_1c1f4050b41311edb0b05d846e82c666, $.Cardinality.Many), null);

const $SubclassableObject = $.makeType(_.spec, "1c24f284-b413-11ed-8aa7-fd1b08e62ef7", _.syntax.literal);

const SubclassableObject= _.syntax.$PathNode($.$toSet($SubclassableObject, $.Cardinality.Many), null);

const $InheritingObject = $.makeType(_.spec, "1cd26e5a-b413-11ed-a96a-bffa16df0245", _.syntax.literal);

const InheritingObject= _.syntax.$PathNode($.$toSet($InheritingObject, $.Cardinality.Many), null);

const $AnnotationSubject = $.makeType(_.spec, "1cbd4c6e-b413-11ed-97a4-65781ce249d9", _.syntax.literal);

const AnnotationSubject= _.syntax.$PathNode($.$toSet($AnnotationSubject, $.Cardinality.Many), null);

const $AccessPolicy = $.makeType(_.spec, "1d69cb06-b413-11ed-8be3-073f59d0920f", _.syntax.literal);

const AccessPolicy= _.syntax.$PathNode($.$toSet($AccessPolicy, $.Cardinality.Many), null);

const $Alias = $.makeType(_.spec, "1d83ec2a-b413-11ed-8e8b-913da5ea6a24", _.syntax.literal);

const Alias= _.syntax.$PathNode($.$toSet($Alias, $.Cardinality.Many), null);

const $Annotation = $.makeType(_.spec, "1cc3f640-b413-11ed-810e-8d2442495cc1", _.syntax.literal);

const Annotation= _.syntax.$PathNode($.$toSet($Annotation, $.Cardinality.Many), null);

const $Type = $.makeType(_.spec, "1c2dbb44-b413-11ed-8e70-3955c08d7e2a", _.syntax.literal);

const Type= _.syntax.$PathNode($.$toSet($Type, $.Cardinality.Many), null);

const $PrimitiveType = $.makeType(_.spec, "1c4d031e-b413-11ed-b2e7-13dcffd2c22b", _.syntax.literal);

const PrimitiveType= _.syntax.$PathNode($.$toSet($PrimitiveType, $.Cardinality.Many), null);

const $CollectionType = $.makeType(_.spec, "1c778ea4-b413-11ed-af75-adb496c0e46c", _.syntax.literal);

const CollectionType= _.syntax.$PathNode($.$toSet($CollectionType, $.Cardinality.Many), null);

const $Array = $.makeType(_.spec, "1c831f6c-b413-11ed-a9fb-47bb53fa5c84", _.syntax.literal);

const Array= _.syntax.$PathNode($.$toSet($Array, $.Cardinality.Many), null);

const $CallableObject = $.makeType(_.spec, "1cebf06e-b413-11ed-ab31-a1de67eb29d4", _.syntax.literal);

const CallableObject= _.syntax.$PathNode($.$toSet($CallableObject, $.Cardinality.Many), null);

const $VolatilitySubject = $.makeType(_.spec, "1cfb2de0-b413-11ed-bc4a-af56ae54fdb0", _.syntax.literal);

const VolatilitySubject= _.syntax.$PathNode($.$toSet($VolatilitySubject, $.Cardinality.Many), null);

const $Cast = $.makeType(_.spec, "1f08a6f8-b413-11ed-bd1a-77b24ab737bc", _.syntax.literal);

const Cast= _.syntax.$PathNode($.$toSet($Cast, $.Cardinality.Many), null);

const $ConsistencySubject = $.makeType(_.spec, "1d1e9e10-b413-11ed-ab48-1f7511ebdacc", _.syntax.literal);

const ConsistencySubject= _.syntax.$PathNode($.$toSet($ConsistencySubject, $.Cardinality.Many), null);

const $Constraint = $.makeType(_.spec, "1d02d66c-b413-11ed-b164-0de1731034b2", _.syntax.literal);

const Constraint= _.syntax.$PathNode($.$toSet($Constraint, $.Cardinality.Many), null);

const $Delta = $.makeType(_.spec, "1cb5278c-b413-11ed-9642-d7b077c16f4f", _.syntax.literal);

const Delta= _.syntax.$PathNode($.$toSet($Delta, $.Cardinality.Many), null);

const $Extension = $.makeType(_.spec, "1f308970-b413-11ed-9c4e-13466e5b206e", _.syntax.literal);

const Extension= _.syntax.$PathNode($.$toSet($Extension, $.Cardinality.Many), null);

const $Function = $.makeType(_.spec, "1ed7a396-b413-11ed-8690-5de9204cc1ce", _.syntax.literal);

const Function= _.syntax.$PathNode($.$toSet($Function, $.Cardinality.Many), null);

const $FutureBehavior = $.makeType(_.spec, "1f407f06-b413-11ed-91cc-07972ba865cb", _.syntax.literal);

const FutureBehavior= _.syntax.$PathNode($.$toSet($FutureBehavior, $.Cardinality.Many), null);

const $Global = $.makeType(_.spec, "1ec451d8-b413-11ed-832f-3d3ca7159813", _.syntax.literal);

const Global= _.syntax.$PathNode($.$toSet($Global, $.Cardinality.Many), null);

const $Index = $.makeType(_.spec, "1d2c2d32-b413-11ed-a987-977b6a63c3c4", _.syntax.literal);

const Index= _.syntax.$PathNode($.$toSet($Index, $.Cardinality.Many), null);

const $Pointer = $.makeType(_.spec, "1d4d1ac4-b413-11ed-b760-5f730cf3f19a", _.syntax.literal);

const Pointer= _.syntax.$PathNode($.$toSet($Pointer, $.Cardinality.Many), null);

const $Source = $.makeType(_.spec, "1d414ffa-b413-11ed-bebe-fbb61095d407", _.syntax.literal);

const Source= _.syntax.$PathNode($.$toSet($Source, $.Cardinality.Many), null);

const $Link = $.makeType(_.spec, "1e33d248-b413-11ed-86a2-3786aba4b3a4", _.syntax.literal);

const Link= _.syntax.$PathNode($.$toSet($Link, $.Cardinality.Many), null);

const $Migration = $.makeType(_.spec, "1f1e5f70-b413-11ed-8ac5-d927e5131911", _.syntax.literal);

const Migration= _.syntax.$PathNode($.$toSet($Migration, $.Cardinality.Many), null);

const $Module = $.makeType(_.spec, "1c47023e-b413-11ed-b9f8-373e00a953fc", _.syntax.literal);

const Module= _.syntax.$PathNode($.$toSet($Module, $.Cardinality.Many), null);

const $ObjectType = $.makeType(_.spec, "1db3da48-b413-11ed-b0b0-c13cf29c58c8", _.syntax.literal);

const ObjectType= _.syntax.$PathNode($.$toSet($ObjectType, $.Cardinality.Many), null);

const $Operator = $.makeType(_.spec, "1ef0e7ca-b413-11ed-b8e5-2174313a2546", _.syntax.literal);

const Operator= _.syntax.$PathNode($.$toSet($Operator, $.Cardinality.Many), null);

const $Parameter = $.makeType(_.spec, "1ce15988-b413-11ed-b7b1-d38606e514be", _.syntax.literal);

const Parameter= _.syntax.$PathNode($.$toSet($Parameter, $.Cardinality.Many), null);

const $Property = $.makeType(_.spec, "1e5fb714-b413-11ed-8d14-b18f3929a0c9", _.syntax.literal);

const Property= _.syntax.$PathNode($.$toSet($Property, $.Cardinality.Many), null);

const $PseudoType = $.makeType(_.spec, "1c36a63c-b413-11ed-923c-596c37eadcca", _.syntax.literal);

const PseudoType= _.syntax.$PathNode($.$toSet($PseudoType, $.Cardinality.Many), null);

const $Range = $.makeType(_.spec, "1ca6de2a-b413-11ed-9c2d-2794a5a60f14", _.syntax.literal);

const Range= _.syntax.$PathNode($.$toSet($Range, $.Cardinality.Many), null);

const $ScalarType = $.makeType(_.spec, "1d92341a-b413-11ed-98ad-37aa5b8cc590", _.syntax.literal);

const ScalarType= _.syntax.$PathNode($.$toSet($ScalarType, $.Cardinality.Many), null);

const $Tuple = $.makeType(_.spec, "1c96b0d6-b413-11ed-a7bd-bbc2054a3b8b", _.syntax.literal);

const Tuple= _.syntax.$PathNode($.$toSet($Tuple, $.Cardinality.Many), null);

const $TupleElement = $.makeType(_.spec, "1c9178f0-b413-11ed-8b4a-a3cdc3deb775", _.syntax.literal);

const TupleElement= _.syntax.$PathNode($.$toSet($TupleElement, $.Cardinality.Many), null);



export { AccessKind, AccessPolicyAction, Cardinality, OperatorKind, ParameterKind, SourceDeleteAction, TargetDeleteAction, TypeModifier, Volatility, $Object_1c1f4050b41311edb0b05d846e82c666, Object_1c1f4050b41311edb0b05d846e82c666, $SubclassableObject, SubclassableObject, $InheritingObject, InheritingObject, $AnnotationSubject, AnnotationSubject, $AccessPolicy, AccessPolicy, $Alias, Alias, $Annotation, Annotation, $Type, Type, $PrimitiveType, PrimitiveType, $CollectionType, CollectionType, $Array, Array, $CallableObject, CallableObject, $VolatilitySubject, VolatilitySubject, $Cast, Cast, $ConsistencySubject, ConsistencySubject, $Constraint, Constraint, $Delta, Delta, $Extension, Extension, $Function, Function, $FutureBehavior, FutureBehavior, $Global, Global, $Index, Index, $Pointer, Pointer, $Source, Source, $Link, Link, $Migration, Migration, $Module, Module, $ObjectType, ObjectType, $Operator, Operator, $Parameter, Parameter, $Property, Property, $PseudoType, PseudoType, $Range, Range, $ScalarType, ScalarType, $Tuple, Tuple, $TupleElement, TupleElement };

const __defaultExports = {
  "AccessKind": AccessKind,
  "AccessPolicyAction": AccessPolicyAction,
  "Cardinality": Cardinality,
  "OperatorKind": OperatorKind,
  "ParameterKind": ParameterKind,
  "SourceDeleteAction": SourceDeleteAction,
  "TargetDeleteAction": TargetDeleteAction,
  "TypeModifier": TypeModifier,
  "Volatility": Volatility,
  "Object": Object_1c1f4050b41311edb0b05d846e82c666,
  "SubclassableObject": SubclassableObject,
  "InheritingObject": InheritingObject,
  "AnnotationSubject": AnnotationSubject,
  "AccessPolicy": AccessPolicy,
  "Alias": Alias,
  "Annotation": Annotation,
  "Type": Type,
  "PrimitiveType": PrimitiveType,
  "CollectionType": CollectionType,
  "Array": Array,
  "CallableObject": CallableObject,
  "VolatilitySubject": VolatilitySubject,
  "Cast": Cast,
  "ConsistencySubject": ConsistencySubject,
  "Constraint": Constraint,
  "Delta": Delta,
  "Extension": Extension,
  "Function": Function,
  "FutureBehavior": FutureBehavior,
  "Global": Global,
  "Index": Index,
  "Pointer": Pointer,
  "Source": Source,
  "Link": Link,
  "Migration": Migration,
  "Module": Module,
  "ObjectType": ObjectType,
  "Operator": Operator,
  "Parameter": Parameter,
  "Property": Property,
  "PseudoType": PseudoType,
  "Range": Range,
  "ScalarType": ScalarType,
  "Tuple": Tuple,
  "TupleElement": TupleElement
};
export default __defaultExports;
