// GENERATED by @edgedb/generate v0.0.7
// Run 'npx @edgedb/generate edgeql-js' to re-generate

export * as edgedb from "edgedb";
export { spec } from "./__spec__.mjs";
export * as syntax from "./syntax.mjs";
export * as castMaps from "./castMaps.mjs";
