// GENERATED by @edgedb/generate v0.0.7
// Run 'npx @edgedb/generate edgeql-js' to re-generate

export * from "./external.mjs";
export { createClient } from "edgedb";
import * as $ from "./reflection.mjs";
import * as $syntax from "./syntax.mjs";
import * as $op from "./operators.mjs";
import _std from "./modules/std.mjs";
import _cal from "./modules/cal.mjs";
import _cfg from "./modules/cfg.mjs";
import _default from "./modules/default.mjs";
import _schema from "./modules/schema.mjs";
import _sys from "./modules/sys.mjs";
import _math from "./modules/math.mjs";

const ExportDefault
 = {
  ..._std,
  ..._default,
  ...$.util.omitDollarPrefixed($syntax),
  ...$op,
  "std": _std,
  "cal": _cal,
  "cfg": _cfg,
  "default": _default,
  "schema": _schema,
  "sys": _sys,
  "math": _math,
};
const Cardinality = $.Cardinality;


export default ExportDefault;
export { Cardinality };
