// GENERATED by @edgedb/generate v0.0.7
// Run 'npx @edgedb/generate edgeql-js' to re-generate

import type * as edgedb from "edgedb";
export declare function $queryFunc(this: any, cxn: edgedb.Executor, args: any): Promise<unknown>;
export declare function $queryFuncJSON(this: any, cxn: edgedb.Executor, args: any): Promise<string>;
