// GENERATED by @edgedb/generate v0.0.7
// Run 'npx @edgedb/generate edgeql-js' to re-generate

import { TypeKind } from "edgedb/dist/reflection/index.js";
export function $toSet(root, card) {
    return {
        __element__: root,
        __cardinality__: card
    };
}
export function isScalarType(type) {
    return type.__kind__ === TypeKind.scalar;
}
export function isEnumType(type) {
    return type.__kind__ === TypeKind.enum;
}
export function isObjectType(type) {
    return type.__kind__ === TypeKind.object;
}
export function isTupleType(type) {
    return type.__kind__ === TypeKind.tuple;
}
export function isNamedTupleType(type) {
    return type.__kind__ === TypeKind.namedtuple;
}
export function isArrayType(type) {
    return type.__kind__ === TypeKind.array;
}
