// GENERATED by @edgedb/generate v0.0.7
// Run 'npx @edgedb/generate edgeql-js' to re-generate

import { ExpressionKind } from "edgedb/dist/reflection/index.js";
import { $expressionify } from "./path.mjs";
export function alias(expr) {
    return $expressionify({
        __kind__: ExpressionKind.Alias,
        __element__: expr.__element__,
        __cardinality__: expr.__cardinality__,
        __expr__: expr
    });
}
function _with(refs, expr) {
    return $expressionify({
        __kind__: ExpressionKind.With,
        __element__: expr.__element__,
        __cardinality__: expr.__cardinality__,
        __refs__: refs,
        __expr__: expr
    });
}
export { _with as with };
